// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// Next.js only auto-loads .env.local at runtime, not for CLI tools like the
// Prisma CLI — load it explicitly here so `prisma migrate`/`studio`/etc. see
// the same DATABASE_URL the app itself uses, instead of maintaining two
// separate env files with the same secret.
config({ path: ".env.local" });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
